Update dotfiles setup (2022/12) (#242)
* Remove vscode atom-keybindings

* Use brave instead of opera

* Install krisp, yarn

* comment out iproute2mac

The error on gh-actions:

```
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink bin/2to3-3.11
Target /usr/local/bin/2to3-3.11
already exists. You may want to remove it:
  rm '/usr/local/bin/2to3-3.11'

To force the link and overwrite all conflicting files:
  brew link --overwrite python@3.11

To list all files that would be deleted:
  brew link --overwrite --dry-run python@3.11

Possible conflicting files are:
/usr/local/bin/2to3-3.11 -> /Library/Frameworks/Python.framework/Versions/3.11/bin/2to3-3.11
/usr/local/bin/idle3.11 -> /Library/Frameworks/Python.framework/Versions/3.11/bin/idle3.11
/usr/local/bin/pydoc3.11 -> /Library/Frameworks/Python.framework/Versions/3.11/bin/pydoc3.11
/usr/local/bin/pyth[Ion3.11 -> /Library/Frameworks/Python.framework/Versions/3.11/bin/python3.11
/usr/local/bin/python3.11-config -> /Library/Frameworks/Python.framework/Versions/3.11/bin/python3.11-config
==> /usr/local/Cellar/python@3.11/3.11.0/bin/python3.11 -m ensurepip
==> /usr/local/Cellar/python@3.11/3.11.0/bin/python3.11 -m pip install -v --no-d
==> Summary
🍺  /usr/local/Cellar/python@3.11/3.11.0: 3,163 files, 61.3MB
==> Installing iproute2mac
==> Pouring iproute2mac--1.4.1.all.bottle.1.tar.gz
🍺  /usr/local/Cellar/iproute2mac/1.4.1: 6 files, 29.5KB
==> Running `brew cleanup iproute2mac`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
Installing iproute2mac has failed!
```

* Fix brew installation

* Add more fonts

No need to install powerline since iTerm2 can configure
"Use build-in Powerline glyphs" setting

* Update .bashrc / .zshrc

* Bump ruby patch version

* No overrite `.gitconfig`

* Remove defaults command

since it doesn't work on Apple Silicon

* Add cloudflare-warp

* Update .gitconfig

* gh pr checks --watch

* Use `~/.config/git/ignore` for global gitignore

* Update dependabot.yml